package com.opnitech.release.services.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.opnitech.release.services.model.Foo1;
import com.opnitech.release.services.service.Foo1LocalServiceUtil;

/**
 * The extended model base implementation for the Foo1 service. Represents a row in the &quot;release_dependency_management_Foo1&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Foo1Impl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Foo1Impl
 * @see com.opnitech.release.services.model.Foo1
 * @generated
 */
public abstract class Foo1BaseImpl extends Foo1ModelImpl implements Foo1 {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a foo1 model instance should use the {@link Foo1} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            Foo1LocalServiceUtil.addFoo1(this);
        } else {
            Foo1LocalServiceUtil.updateFoo1(this);
        }
    }
}
